### ISSUE TITLE
example to navigation pages 

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [m7amad-7asan/rn-animated-tabbar#1]
good job but I need an example with the react-native navigation bottom bar of how to render different pages I tried with different ways but all ways failed and how to style text for responsive or where are props for both text and bottom bar  I try to add one screen it is broken all the style what about responsive? thanks for all.

**Comment by m7amad-7asan** [comment]
Thanks Ahmad,

1- The id of the tab should be the name of the tab you want to navigate as it named in your tabs navigator
2- In the navigationHandler you can navigate to the screen using the screen name returned

example:

const {navigate} = useNavigation();

<BottomTabs 
        tabsData={BottomTabsData} 
        tabBarBackground="#513070"
        activeTabBackground="#FFFFFF"
        textColor="#FFFFFF"
        navigationHandler={(screen: string) => { 
            // screen is the id of the tab
            navigate(screen)
        }}
    />
